<?php require("templates/header.phtml") ?>

<div class='contenedor-tarjeta-artista'>
    <?php foreach ($artistas as $artista): ?>
        <div class='artist-tarjeta'>
            <a href='artista/<?= $artista->id ?>'><?= $artista->nombre_artista ?></a>
        </div>
    <?php endforeach; ?>
</div>
<?php if(SesionHelper::isAdmin()): ?>
    <?php require("templates/artistAgregar.phtml") ?>
<?php endif;?>

<?php require("templates/footer.phtml") ?>