<div class='contenedor-artist-control'>

    <div style="padding-right: 100px;">
        <p style="font-size: 3em;">Control Panel</p>

    </div>
    <div style="padding-left: 100px;">
        <p style="font-size: 3em;">Editar artista</p>

        <form id="" action='editArtista/<?= $artista->id ?>' method='post'>


            <label for=''>Nombre artístico</label>
            <input type='text' name='artist-name'>

            <label for=''>Descripcion</label>
            <textarea name='artist-desc' id='' cols='30' rows='10'></textarea>

            <label for=''>Edad</label>
            <input type='text' name='artist-edad'>

            <label for=''>Nacionalidad</label>
            <input type='text' name='artist-nac'>

            <button type='submit'>Editar</button>
        </form>
    </div>



</div>