<?php 
include 'header.phtml'; 

echo "
    <div class='contenedorArtista'>
      <div>
        <h2>Artista</h2>
        <h3>$artista->nombre_artista</h3>
      </div>
      <div>
      <h2>Descripcion</h2>
      <p>$artista->descripcion</p>
      </div>
      <div>
      <h4>Nacionalidad</h4>
      <p>$artista->nacionalidad</p>
      <p>Edad: $artista->edad</p>
      </div>
    </div>";

include 'footer.phtml'; 

?>
