
<div>
    <table>
        <thead>
            <tr>
                <td>Número</td>
                <td>Nombre</td>
                <td>Artista</td>
                <td>Album</td>
            </tr>    
        </thead>
        <tbody>
        <?php foreach ($canciones as $cancion): ?>
            <tr> 
                <td><?= $cancion->id_cancion?></td>   
                <td><a href="cancion/<?= $cancion->id_cancion?>"><?=$cancion->nombre_cancion?></a></td>
                <td><?=$cancion->nombre_artista?></td>
                <td><?=$cancion->album?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>    
    </table>
</div>

