<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500&display=swap" rel="stylesheet">
    <title>Artistas</title>
    <base href=<?php echo BASE_URL; ?>>
</head>

<body>
    <header>
        <h1><a href="inicio">Artistas</a></h1>
        <nav>
            <a href="canciones">Lista de canciones</a>
            <?php if (!SesionHelper::isLogged()) { ?>
                <a href="<?php echo BASE_URL; ?>login">Login</a>
            <?php } else { ?>
                <a href="<?php echo BASE_URL; ?>logout">Logout</a>
            <?php } ?>
        </nav>

        </nav>
    </header>