<?php include './templates/header.phtml'; ?>

<div class="contenedor-form">
    <div class="form-tarjeta">
        <form action="login" method="post">
            <div class="form-group">
                <label for="">Ingresa tu nombre de usuario</label>
                <input type="username" name="usuario">
            </div>
            <div class="form-group">

                <label for="">Ingresa tu contraseña</label>
                <input type="password" name="password">
            </div>

            <?php if ($error): ?>
                <div class='alert alert-danger' role='alert'>
                    <?= $error ?>
                </div>
            <?php endif ?>

            <button type="submit">Registrar</button>

        </form>
        <div>
            <p>¿Ya tienes cuenta?</p>
            <a href="login">Loguear</a>
        </div>
    </div>
</div>



<?php include './templates/footer.phtml'; ?>